[package]
name = "08-space-image-format"
version = "0.1.0"
authors = ["df5602 <dominik@fankhausers.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-util = { git = "https://github.com/df5602/aoc-util" }
